src/VS2015/UI/Controllers/ReadServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using KakashiService.Core.Entities;
using KakashiService.Core.Services;
using KakashiService.Web.ViewModel;

namespace KakashiService.Web.Controllers
{
    public class ReadServiceController : Controller
    {
        private ReadService _readService;
        public ReadServiceController()
        {
            _readService = new ReadService();
        }

        public ActionResult Index()
        {
            return View(new ConfigurationVM(true));
        }

        [HttpPost]
        public JsonResult Read(String Url)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false });
            }
            var serviceObject = new ServiceObject(){Url = Url};
            try
            {
                _readService.Execute(serviceObject);
                var response = PrepareResponse(serviceObject);
                return Json(new { success = true, response }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {             
                return Json(new { success = false, modal = new { title = "Operation Fail!" } }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ImportFile()
        {
            var file = HttpContext.Request.Files[0];
            var stream = file.InputStream;

            var serviceObject = new ServiceObject();
            serviceObject.FileStream = stream;
            _readService.Execute(serviceObject);
            var response = PrepareResponse(serviceObject);
            return Json(new { success = true, response }, JsonRequestBehavior.AllowGet);
        }

        private object PrepareResponse(ServiceObject serviceObject)
        {
            var functionList = new List<String>();
            foreach (var function in serviceObject.Functions)
            {
                var parameters = String.Empty;
                foreach (var parameter in function.Parameters.OrderBy(a => a.Order))
                {
                    var comma = parameter.Order == function.Parameters.Max(a => a.Order) ? String.Empty : ", ";
                    parameters += parameter.Type + comma;
                }
                functionList.Add(String.Format("{0} {1}({2});", function.ReturnType, function.Name, parameters));
            }
            var name = serviceObject.OriginServiceName;
            var totalObject = serviceObject.ObjectTypes.Count;
            var objectList = new List<String>();
            foreach (var objectType in serviceObject.ObjectTypes)
            {
                var parameters = String.Empty;
                foreach (var attribute in objectType.Attributes)
                {
                    var comma = objectType.Attributes.Any(a => attribute == a) ? ", " : "";
                    parameters += attribute+comma;
                }
                objectList.Add(String.Format("{0} - ({1});", objectType.Type, parameters));
            }
            return new {name, totalFunctions = serviceObject.Functions.Count, functions = functionList, totalObject, objects = objectList};
        }
    }
}

src/VS2015/UI/Controllers/RegistrationController.cs
using KakashiService.Core.Services;
using KakashiService.Web.ViewModel;
using System;
using System.IO;
using System.Web.Mvc;
using KakashiService.Core.Entities;

namespace KakashiService.Web.Controllers
{
    public class RegistrationController : Controller
    {
        public ActionResult Index()
        {
            return View(new ConfigurationVM(true));
        }

        [HttpPost]
        public JsonResult Register(ConfigurationVM config)
        {
            var message = "Service " + config.ServiceName + " Cloned!";

            if (!ModelState.IsValid)
            {
                return Json(new { success = false });
            }
            var serviceObject = new ServiceObject();
            ConfigurationVM.Convert(serviceObject, config);

            var bytes = Session["stream"] as byte[];
            if (bytes != null)
            {                
                var stream = new MemoryStream(bytes);
                serviceObject.FileStream = stream;
            }

            var main = new MainService();
            try
            {                
                main.Execute(serviceObject);
                message += String.Format("\nEndpoint: http://{0}:{1}/{2}.svc?wsdl", Request.UrlReferrer.Host, serviceObject.Port, serviceObject.Name);
                return Json(new { success = true, modal = new { message, title = "Operation Completed!" } }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                message = "Error cloning! ("+e.Message+")";
                return Json(new { success = false, modal = new { message, title = "Operation Fail!" } }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ImportFile()
        {
            var file = HttpContext.Request.Files[0];
            var tempStream = new MemoryStream();
            file.InputStream.CopyTo(tempStream);
            Session["stream"] = tempStream.ToArray();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

src/VS2015/UI/Views/ReadService/Index.cshtml
@model KakashiService.Web.ViewModel.ConfigurationVM
@{
    ViewBag.Title = "Read Service";
}
<ul class="nav nav-tabs">
    <li role="presentation" ><a href="@Url.Action("Index","Registration")"  role="tab" >Registration</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("Index","ReadService")"  role="tab" >Read Service</a></li>
</ul>
<div class="tab-pane active">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="control-label">Endpoint:</label>
                        <input id="Url" type="text" class="form-control" placeholder="Type your endpoint to be read" value="@Model.Url" />
                    </div>
                    <label class="control-label">OR</label>
                    <div class="form-group">
                        <label class="control-label">Import:</label>
                        <div id="fine-uploader-import"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="response" class="col-xs-12">
                    <div id="nameService">
                    </div>
                    <div id="functions">
                    </div>
                    <div id="objects">
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-xs-12">
                    <div class="pull-right">
                        <input id="btnForm" type="button" class="btn btn-primary" value="Read!">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="result">
    </div>
</div>
<script type="text/template" id="qq-template">
        <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Upload a file</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <div class="qq-progress-bar-container-selector">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                    <span class="qq-upload-file-selector qq-upload-file"></span>
                    <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                    <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                    <span class="qq-upload-size-selector qq-upload-size"></span>
                    <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                    <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button>
                    <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>
@section scripts{
    <script src="~/Scripts/fine-uploader.js"></script>
    <script src="~/Scripts/ReadService/Index.js"></script>
}

src/VS2015/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Kakashi Service@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" >
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/Content/fine-uploader.css" rel="stylesheet" />
    <meta name="description" content="Kakashi Service UI" />
</head>
<body>
<div class="container">
    <div class="page-header">
        <h2>Kakashi Service</h2>
    </div>
    @RenderBody()
    <div class="loader hidden"></div>
</div>

    <script>
    @{
        var urlRoot = HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority) + Url.Content("~");
        urlRoot = !string.IsNullOrWhiteSpace(urlRoot) && urlRoot.EndsWith("/") ? urlRoot.Remove(urlRoot.Length - 1) : urlRoot;
    }
    var urlRoot = '@urlRoot';
    </script>
    <script src="~/Scripts/jquery.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/Global.js"></script>
    @RenderSection("scripts")
</body>
</html>